// 国际化 — 中英文对照表

const i18n = {
  zh: {
    // 通用
    save: "保存", cancel: "取消", confirm: "确定", delete: "删除",
    add: "新增", edit: "编辑", export: "导出", import: "导入",
    reset: "重置", logout: "退出", login: "登录", update: "更新",
    actions: "操作", loading: "加载中…",
    // 品牌
    brandName: "恺皓资本", brandTagline: "专业资产管理，稳健增值",
    // 登录
    entryPortal: "身份入口", entryDesc: "选择身份后进入对应视图",
    investorLogin: "投资者登录", adminLogin: "管理员登录",
    switchToAdmin: "切换管理员", switchToInvestor: "切换投资者",
    investorId: "投资者编号", username: "用户名", password: "密码",
    phoneLastFour: "手机号后四位",

    investorLoginHint: "输入姓名与密码登录", adminLoginHint: "输入管理员用户名与密码",
    // 导航 / 状态
    platformOverview: "平台概览", adminConsole: "管理后台",
    verifiedAccess: "已验证", currentUser: "当前", notLoggedIn: "未登录",
    snapshot: "快照", investorCount: "位投资者", investorCountLabel: "投资者人数", backToMenu: "返回主菜单",
    // 平台 KPI
    totalPrincipal: "管理本金", latestValuation: "最新估值",
    cumulativeReturn: "累计收益",
    // 投资者面板
    investorProfile: "投资者资料", allocations: "投资方向",
    notices: "沟通纪要",
    bestAllocation: "最佳方向", totalInvested: "累计投入",
    profit: "浮动盈亏", returnRate: "累计收益率",
    riskLevel: "风险偏好", advisor: "顾问团队",
    joinedAt: "建仓日期", lastReview: "最近更新",
    email: "联系邮箱", phone: "手机号码", name: "姓名",
    directionName: "方向名称", directionFocus: "投资说明",
    directionCode: "策略代码", amountInvested: "投入金额",
    latestValue: "最新估值",
    noticeDate: "纪要日期", noticeTitle: "纪要标题", noticeDetail: "纪要详情",
    // 管理后台
    adminConsoleDesc: "管理投资者与沟通纪要，导入导出数据",
    userManagement: "用户管理", userManagementDesc: "新增、编辑、删除投资者账号",
    productManagement: "产品管理", productManagementDesc: "录入产品名称、投资平台、出入金明细、备注等信息",
    dataManagement: "数据管理", dataManagementDesc: "导出 JSON、导入 JSON / Excel、重置数据",
    addUser: "新增投资者",
    loginUsernames: "登录用户名", loginUsernamesPlaceholder: "输入用户名后点击添加",
    exportData: "导出数据", exportDataDesc: "将当前所有平台数据导出为 JSON 文件，用于备份或迁移。",
    importData: "导入数据", importDataDesc: "从 JSON 或 Excel 文件导入数据，JSON 导入将覆盖当前数据，Excel 导入将追加投资者。",
    excelFormat: "Excel 列头格式",
    resetDemoData: "重置数据", resetDemoDataDesc: "清除所有当前数据，恢复为空数据状态，此操作不可撤销。",
    dataStructureNote: "数据结构说明",
    dataStructureDesc: "数据以标准 JSON 格式持久化到浏览器 localStorage。可直接映射为后端数据库表：investors、allocations、notices、admin_users。接入真实后台时，替换 数据操作.js 中的 loadData / saveData 即可无缝迁移。",
    exportJSON: "导出 JSON", importJSON: "导入 JSON",
    importExcel: "导入 Excel", resetData: "重置数据",
    selectInvestor: "选择投资者", saveInvestor: "保存资料",
    addAllocation: "添加投资方向",
    addNotice: "保存纪要",
    // 提示
    flashLoggedIn: "登录成功，欢迎回来。",
    flashLoggedOut: "已退出登录。",
    flashLoginFailed: "账号或密码错误，请重试。",
    flashSaved: "已保存。",
    flashDeleted: "已删除。",
    flashImported: "数据导入成功。", flashImportedCount: "数据导入成功，共处理 {n} 条。",
    flashExported: "数据导出成功。",
    flashReset: "数据已重置。",
    flashError: "操作失败，请检查填写内容。",
    noData: "暂无数据",
    noAllocations: "尚未录入投资方向",
    noNotices: "尚未录入沟通纪要",
    // 风险等级
    riskConservative: "稳健型", riskBalanced: "平衡型", riskAggressive: "进取型",
    riskLow: "低风险", riskMedium: "中风险", riskHigh: "高风险",
    totalInvestment: "累计投入",
    investorList: "投资者列表",
    total: "共",
    // 确认提示
    confirmDeleteInvestor: "确定要删除投资者 {id} 的所有数据吗？此操作不可撤销。",
    confirmDeleteProduct: "确定要删除产品吗？",
    confirmResetData: "确定要重置所有数据为空数据状态吗？",
    // 错误提示
    errorInvestorIdRequired: "投资者编号不能为空。",
    errorNameRequired: "姓名不能为空。",
    errorPasswordRequired: "密码不能为空。",
    errorPasswordMismatch: "两次密码输入不一致。",
    errorInvestorNotFound: "未找到投资者。",
    errorAmountRequired: "金额不能为空或零。",
    errorImportFailed: "导入失败：{msg}",
    errorExcelImportFailed: "Excel 导入失败：{msg}",
    errorProductNotFound: "未找到产品。",
    accountCreated: "账户建立", accountCreatedDetail: "账户已录入平台。",
    // 产品管理
    product: "产品", productName: "产品名称", productCode: "产品代码",
    platform: "投资平台", transactions: "出入金明细",
    deposit: "入金", withdrawal: "出金", netAmount: "净金额",
    totalDeposits: "总入金", totalWithdrawals: "总出金",
    notes: "备注", noTransactions: "暂无交易记录",
    amount: "金额", note: "备注", transaction: "交易记录",
  },
  en: {
    save: "Save", cancel: "Cancel", confirm: "Confirm", delete: "Delete",
    add: "Add", edit: "Edit", export: "Export", import: "Import",
    reset: "Reset", logout: "Logout", login: "Login", update: "Update",
    actions: "Actions", loading: "Loading…",
    brandName: "KaiHao Capital", brandTagline: "Professional Asset Management",
    entryPortal: "Entry", entryDesc: "Select your identity to continue",
    investorLogin: "Investor Login", adminLogin: "Admin Login",
    switchToAdmin: "Switch to Admin", switchToInvestor: "Switch to Investor",
    investorId: "Investor ID", username: "Username", password: "Password",
    phoneLastFour: "Last 4 digits of phone",

    investorLoginHint: "Enter name and password to login", adminLoginHint: "Enter admin username and password",
    // 导航 / 状态
    platformOverview: "Platform Overview", adminConsole: "Admin Console",
    verifiedAccess: "Verified", currentUser: "Current", notLoggedIn: "Not logged in",
    snapshot: "Snapshot", investorCount: "investors", investorCountLabel: "Investor Count", backToMenu: "Back to Menu",
    totalPrincipal: "AUM", latestValuation: "Latest Value",
    cumulativeReturn: "Total Return",
    investorProfile: "Profile", allocations: "Allocations",
    notices: "Notices",
    bestAllocation: "Best Direction", totalInvested: "Invested",
    profit: "P&L", returnRate: "Total Return",
    riskLevel: "Risk Level", advisor: "Advisor",
    joinedAt: "Inception", lastReview: "Last Review",
    email: "Email", phone: "Phone", name: "Name",
    directionName: "Direction Name", directionFocus: "Description",
    directionCode: "Code", amountInvested: "Amount Invested",
    latestValue: "Latest Value",
    noticeDate: "Date", noticeTitle: "Title", noticeDetail: "Detail",
    adminConsoleDesc: "Manage investors & notices, import/export data",
    userManagement: "User Management", userManagementDesc: "Add, edit, delete investor accounts",
    productManagement: "Product Management", productManagementDesc: "Enter product name, investment platform, deposit/withdrawal details, notes, etc.",
    dataManagement: "Data Management", dataManagementDesc: "Export JSON, Import JSON/Excel, Reset data",
    addUser: "Add Investor",
    loginUsernames: "Login Usernames", loginUsernamesPlaceholder: "Enter username and click Add",
    exportData: "Export Data", exportDataDesc: "Export all platform data as a JSON file for backup or migration.",
    importData: "Import Data", importDataDesc: "Import data from JSON (overwrites) or Excel (appends investors).",
    excelFormat: "Excel Format",
    resetDemoData: "Reset Data", resetDemoDataDesc: "Clear all data and restore empty data state. This cannot be undone.",
    dataStructureNote: "Data Structure",
    dataStructureDesc: "Data is persisted in browser localStorage as standard JSON. Can map directly to backend tables: investors, allocations, notices, admin_users. For real backend integration, replace loadData / saveData in 数据操作.js.",
    exportJSON: "Export JSON", importJSON: "Import JSON",
    importExcel: "Import Excel", resetData: "Reset Data",
    selectInvestor: "Select Investor", saveInvestor: "Save Profile",
    addAllocation: "Add Allocation",
    addNotice: "Save Notice",
    flashLoggedIn: "Login successful. Welcome back.",
    flashLoggedOut: "You have been logged out.",
    flashLoginFailed: "Incorrect credentials. Please try again.",
    flashSaved: "Saved successfully.",
    flashDeleted: "Deleted successfully.",
    flashImported: "Data imported successfully.", flashImportedCount: "Data imported successfully. {n} records processed.",
    flashExported: "Data exported successfully.",
    flashReset: "Data has been reset.",
    flashError: "Operation failed. Please check the inputs.",
    noData: "No data",
    noAllocations: "No allocations recorded",
    noNotices: "No notices recorded",
    riskConservative: "Conservative", riskBalanced: "Balanced", riskAggressive: "Aggressive",
    riskLow: "Low Risk", riskMedium: "Medium Risk", riskHigh: "High Risk",
    totalInvestment: "Total Invested",
    investorList: "Investor List",
    total: "Total",
    confirmDeleteInvestor: "Are you sure you want to delete all data for investor {id}? This cannot be undone.",
    confirmDeleteProduct: "Are you sure you want to delete this product?",
    confirmResetData: "Are you sure you want to reset all data to empty state?",
    errorInvestorIdRequired: "Investor ID cannot be empty.",
    errorNameRequired: "Name is required.",
    errorPasswordRequired: "Password is required.",
    errorPasswordMismatch: "Passwords do not match.",
    errorInvestorNotFound: "Investor not found.",
    errorAmountRequired: "Amount cannot be empty or zero.",
    errorImportFailed: "Import failed: {msg}",
    errorExcelImportFailed: "Excel import failed: {msg}",
    errorProductNotFound: "Product not found.",
    accountCreated: "Account Created", accountCreatedDetail: "Account has been registered.",
    // 产品管理
    product: "Product", productName: "Product Name", productCode: "Product Code",
    platform: "Investment Platform", transactions: "Transactions",
    deposit: "Deposit", withdrawal: "Withdrawal", netAmount: "Net Amount",
    totalDeposits: "Total Deposits", totalWithdrawals: "Total Withdrawals",
    notes: "Notes", noTransactions: "No transactions",
    amount: "Amount", note: "Note", transaction: "Transaction",
  }
};

export default i18n;
