// 国际化 — 语言对照表

const i18n = {
  "zh": {
    // 通用
    save: "保存", cancel: "取消", confirm: "确定", delete: "删除",
    add: "新增", edit: "编辑", export: "导出", import: "导入",
    reset: "重置", logout: "退出", login: "登录", update: "更新",
    actions: "操作", loading: "加载中…",
    // 品牌
    brandName: "恺皓资本", brandTagline: "专业资产管理，稳健增值",
    // 登录
    entryPortal: "身份入口", entryDesc: "选择身份后进入对应视图",
    investorLogin: "投资者登录", adminLogin: "管理员登录",
    switchToAdmin: "切换管理员", switchToInvestor: "切换投资者",
    investorId: "投资者编号", username: "用户名", password: "密码",
    phoneLastFour: "手机号后四位",
    investorLoginHint: "输入姓名与密码登录", adminLoginHint: "输入管理员用户名与密码",
    // 导航 / 状态
    platformOverview: "平台概览", adminConsole: "管理后台",
    verifiedAccess: "已验证", currentUser: "当前", notLoggedIn: "未登录",
    snapshot: "快照", investorCount: "位投资者", investorCountLabel: "投资者人数", backToMenu: "返回主菜单",
    // 平台 KPI
    totalPrincipal: "管理本金", latestValuation: "最新估值",
    cumulativeReturn: "累计收益",
    // 投资者面板
    investorProfile: "投资者资料", allocations: "投资方向",
    notices: "沟通纪要",
    bestAllocation: "最佳方向", totalInvested: "累计投入",
    profit: "浮动盈亏", returnRate: "累计收益率",
    riskLevel: "风险偏好", advisor: "顾问团队",
    joinedAt: "建仓日期", lastReview: "最近更新",
    email: "联系邮箱", phone: "手机号码", name: "姓名",
    directionName: "方向名称", directionFocus: "投资说明",
    directionCode: "策略代码", amountInvested: "投入金额",
    latestValue: "最新估值",
    noticeDate: "纪要日期", noticeTitle: "纪要标题", noticeDetail: "纪要详情",
    // 管理后台
    adminConsoleDesc: "管理投资者与沟通纪要，导入导出数据",
    userManagement: "用户管理", userManagementDesc: "新增、编辑、删除投资者账号",
    productManagement: "产品管理", productManagementDesc: "录入产品名称、投资平台、出入金明细、备注等信息",
    dataManagement: "数据管理", dataManagementDesc: "导出 JSON、导入 JSON / Excel、重置数据",
    addUser: "新增投资者",
    loginUsernames: "登录用户名", loginUsernamesPlaceholder: "输入用户名后点击添加",
    exportData: "导出数据", exportDataDesc: "将当前所有平台数据导出为 JSON 文件，用于备份或迁移。",
    importData: "导入数据", importDataDesc: "从 JSON 或 Excel 文件导入数据，JSON 导入将覆盖当前数据，Excel 导入将追加投资者。",
    excelFormat: "Excel 列头格式",
    resetDemoData: "重置数据", resetDemoDataDesc: "清除所有当前数据，恢复为空数据状态，此操作不可撤销。",
    dataStructureNote: "数据结构说明",
    dataStructureDesc: "数据以标准 JSON 格式持久化到浏览器 localStorage。可直接映射为后端数据库表：investors、allocations、notices、admin_users。接入真实后台时，替换 数据操作.js 中的 loadData / saveData 即可无缝迁移。",
    exportJSON: "导出 JSON", importJSON: "导入 JSON",
    importExcel: "导入 Excel", resetData: "重置数据",
    selectInvestor: "选择投资者", saveInvestor: "保存资料",
    addAllocation: "添加投资方向",
    addNotice: "保存纪要",
    // 提示
    flashLoggedIn: "登录成功，欢迎回来。",
    flashLoggedOut: "已退出登录。",
    flashLoginFailed: "账号或密码错误，请重试。",
    flashSaved: "已保存。",
    flashDeleted: "已删除。",
    flashImported: "数据导入成功。", flashImportedCount: "数据导入成功，共处理 {n} 条。",
    flashExported: "数据导出成功。",
    flashReset: "数据已重置。",
    flashError: "操作失败，请检查填写内容。",
    noData: "暂无数据",
    noAllocations: "尚未录入投资方向",
    noNotices: "尚未录入沟通纪要",
    // 风险等级
    riskConservative: "稳健型", riskBalanced: "平衡型", riskAggressive: "进取型",
    riskLow: "低风险", riskMedium: "中风险", riskHigh: "高风险",
    totalInvestment: "累计投入",
    investorList: "投资者列表",
    total: "共",
    // 确认提示
    confirmDeleteInvestor: "确定要删除投资者 {id} 的所有数据吗？此操作不可撤销。",
    confirmDeleteProduct: "确定要删除产品吗？",
    confirmResetData: "确定要重置所有数据为空数据状态吗？",
    // 错误提示
    errorInvestorIdRequired: "投资者编号不能为空。",
    errorNameRequired: "姓名不能为空。",
    errorPasswordRequired: "密码不能为空。",
    errorPasswordMismatch: "两次密码输入不一致。",
    errorInvestorNotFound: "未找到投资者。",
    errorAmountRequired: "金额不能为空或零。",
    errorImportFailed: "导入失败：{msg}",
    errorExcelImportFailed: "Excel 导入失败：{msg}",
    errorProductNotFound: "未找到产品。",
    accountCreated: "账户建立", accountCreatedDetail: "账户已录入平台。",
    // 产品管理
    product: "产品", productName: "产品名称", productCode: "产品代码",
    platform: "投资平台", transactions: "出入金明细",
    deposit: "入金", withdrawal: "出金", netAmount: "净金额",
    totalDeposits: "总入金", totalWithdrawals: "总出金",
    notes: "备注", noTransactions: "暂无交易记录",
    amount: "金额", note: "备注", transaction: "交易记录",
    // 事件处理提示
    pleaseFillDateAmount: "请填写日期和有效金额",
    fundFlowAdded: "出入金记录已添加",
    confirmDeleteFundFlow: "确认删除此出入金记录？",
    fundFlowDeleted: "出入金记录已删除",
    pleaseAddFundFlowFirst: "请先添加出入金记录",
    allocationExceeds: "分配金额超过净投入",
    allocationUpdated: "产品分配已更新（总计 {n}%）",
    loginAttemptsLeft: "登录失败，还有{n}次尝试机会",
    loginLocked: "登录失败次数过多，账户已被锁定5分钟",
    accountLocked: "账户已被锁定，请{n}分钟后再试",
    pleaseEnterProductCode: "请输入产品代码",
    pleaseEnterProductName: "请输入产品名称",
    pleaseEnterValidAmount: "请输入有效的投资金额",
    pleaseEnterValidValue: "请输入有效的最新价值",
    pleaseSelectProduct: "请选择产品",
    pleaseSelectDate: "请选择日期",
    pleaseEnterValidPrice: "请输入有效的价值",
    pleaseSelectInvestor: "请选择投资者",
    pleaseEnterTitle: "请输入标题",
    pleaseEnterDetail: "请输入详情",
    pleaseEnterPlatform: "请输入平台",
    transactionAmountInvalid: "第{n}条交易记录金额无效",
    transactionDateMissing: "第{n}条交易记录缺少日期",
    pleaseEnterValidInterest: "请输入有效的利息金额",
    interestSaved: "利息记录已保存",
    demoAccount: "演示",
    viewInvestorView: "查看投资者视角",
    backToAdminView: "返回管理员视角",
    viewAsAdmin: "管理员查看",
    undefined: "未定",
    currentStatus: "当前状态",
    versionHistory: "版本更新记录",
    dataUpdateRecord: "数据更新记录",
    netAssetData: "净值 & 资产数据",
    lastUpdateTime: "上次更新时间",
    snapshotDateSaved: "数据更新时间已保存",
    investorNotFound: "投资者信息不存在，请重新登录。",
    adminViewMode: "管理员查看模式",
    backToAdmin: "返回管理后台",
    dataUpdateDate: "数据更新日期：",
    exportPDF: "导出PDF报告",
    totalInterestPaid: "累计发放利息",
    interestCount: "利息发放次数",
    fundDistribution: "资金分布",
    portfolioAllocation: "投资组合占比",
    noInvestmentData: "暂无投资数据",
    interestTrend: "利息发放趋势",
    cumulativeInterest: "累计利息走势",
    productVolatility: "产品波动",
    productValueTrend: "各产品价值变化趋势",
    allPhases: "全部阶段",
    phase2: "第二阶段",
    phase1: "第一阶段",
    noProductData: "暂无产品数据",
    investmentPerformance: "投资表现",
    productReturnAnalysis: "各产品收益分析",
    interestRecords: "利息发放记录",
    recentInterestDetails: "最近发放明细",
    paymentDate: "发放日期",
    paymentPlatform: "发放平台",
    interestAmount: "利息金额",
    remark: "备注",
    portfolioAnalysis: "组合分析",
    riskReturnAssessment: "风险与收益评估",
    investmentProductCount: "投资产品数",
    averageReturn: "平均收益率",
    bestPerformingProduct: "最高收益产品",
    lastUpdated: "最近更新",
    totalValue: "总估值",
    totalProfit: "总收益",
    investmentPeriod: "投资期限",
    days: "天",
    recentNotices: "最近沟通纪要",
    invested: "投入",
    valuation: "估值",
    percentage: "占比",
    return: "收益",
  },
  "en": {
    save: "Save", cancel: "Cancel", confirm: "Confirm", delete: "Delete",
    add: "Add", edit: "Edit", export: "Export", import: "Import",
    reset: "Reset", logout: "Logout", login: "Login", update: "Update",
    actions: "Actions", loading: "Loading…",
    brandName: "KaiHao Capital", brandTagline: "Professional Asset Management",
    entryPortal: "Entry", entryDesc: "Select your identity to continue",
    investorLogin: "Investor Login", adminLogin: "Admin Login",
    switchToAdmin: "Switch to Admin", switchToInvestor: "Switch to Investor",
    investorId: "Investor ID", username: "Username", password: "Password",
    phoneLastFour: "Last 4 digits of phone",
    investorLoginHint: "Enter name and password to login", adminLoginHint: "Enter admin username and password",
    platformOverview: "Platform Overview", adminConsole: "Admin Console",
    verifiedAccess: "Verified", currentUser: "Current", notLoggedIn: "Not logged in",
    snapshot: "Snapshot", investorCount: "investors", investorCountLabel: "Investor Count", backToMenu: "Back to Menu",
    totalPrincipal: "AUM", latestValuation: "Latest Value",
    cumulativeReturn: "Total Return",
    investorProfile: "Profile", allocations: "Allocations",
    notices: "Notices",
    bestAllocation: "Best Direction", totalInvested: "Invested",
    profit: "P&L", returnRate: "Total Return",
    riskLevel: "Risk Level", advisor: "Advisor",
    joinedAt: "Inception", lastReview: "Last Review",
    email: "Email", phone: "Phone", name: "Name",
    directionName: "Direction Name", directionFocus: "Description",
    directionCode: "Code", amountInvested: "Amount Invested",
    latestValue: "Latest Value",
    noticeDate: "Date", noticeTitle: "Title", noticeDetail: "Detail",
    adminConsoleDesc: "Manage investors & notices, import/export data",
    userManagement: "User Management", userManagementDesc: "Add, edit, delete investor accounts",
    productManagement: "Product Management", productManagementDesc: "Enter product name, investment platform, deposit/withdrawal details, notes, etc.",
    dataManagement: "Data Management", dataManagementDesc: "Export JSON, Import JSON/Excel, Reset data",
    addUser: "Add Investor",
    loginUsernames: "Login Usernames", loginUsernamesPlaceholder: "Enter username and click Add",
    exportData: "Export Data", exportDataDesc: "Export all platform data as a JSON file for backup or migration.",
    importData: "Import Data", importDataDesc: "Import data from JSON (overwrites) or Excel (appends investors).",
    excelFormat: "Excel Format",
    resetDemoData: "Reset Data", resetDemoDataDesc: "Clear all data and restore empty data state. This cannot be undone.",
    dataStructureNote: "Data Structure",
    dataStructureDesc: "Data is persisted in browser localStorage as standard JSON. Can map directly to backend tables: investors, allocations, notices, admin_users. For real backend integration, replace loadData / saveData in 数据操作.js.",
    exportJSON: "Export JSON", importJSON: "Import JSON",
    importExcel: "Import Excel", resetData: "Reset Data",
    selectInvestor: "Select Investor", saveInvestor: "Save Profile",
    addAllocation: "Add Allocation",
    addNotice: "Save Notice",
    flashLoggedIn: "Login successful. Welcome back.",
    flashLoggedOut: "You have been logged out.",
    flashLoginFailed: "Incorrect credentials. Please try again.",
    flashSaved: "Saved successfully.",
    flashDeleted: "Deleted successfully.",
    flashImported: "Data imported successfully.", flashImportedCount: "Data imported successfully. {n} records processed.",
    flashExported: "Data exported successfully.",
    flashReset: "Data has been reset.",
    flashError: "Operation failed. Please check the inputs.",
    noData: "No data",
    noAllocations: "No allocations recorded",
    noNotices: "No notices recorded",
    riskConservative: "Conservative", riskBalanced: "Balanced", riskAggressive: "Aggressive",
    riskLow: "Low Risk", riskMedium: "Medium Risk", riskHigh: "High Risk",
    totalInvestment: "Total Invested",
    investorList: "Investor List",
    total: "Total",
    confirmDeleteInvestor: "Are you sure you want to delete all data for investor {id}? This cannot be undone.",
    confirmDeleteProduct: "Are you sure you want to delete this product?",
    confirmResetData: "Are you sure you want to reset all data to empty state?",
    errorInvestorIdRequired: "Investor ID cannot be empty.",
    errorNameRequired: "Name is required.",
    errorPasswordRequired: "Password is required.",
    errorPasswordMismatch: "Passwords do not match.",
    errorInvestorNotFound: "Investor not found.",
    errorAmountRequired: "Amount cannot be empty or zero.",
    errorImportFailed: "Import failed: {msg}",
    errorExcelImportFailed: "Excel import failed: {msg}",
    errorProductNotFound: "Product not found.",
    accountCreated: "Account Created", accountCreatedDetail: "Account has been registered.",
    product: "Product", productName: "Product Name", productCode: "Product Code",
    platform: "Investment Platform", transactions: "Transactions",
    deposit: "Deposit", withdrawal: "Withdrawal", netAmount: "Net Amount",
    totalDeposits: "Total Deposits", totalWithdrawals: "Total Withdrawals",
    notes: "Notes", noTransactions: "No transactions",
    amount: "Amount", note: "Note", transaction: "Transaction",
    pleaseFillDateAmount: "Please fill in date and valid amount",
    fundFlowAdded: "Fund flow record added",
    confirmDeleteFundFlow: "Confirm deleting this fund flow record?",
    fundFlowDeleted: "Fund flow record deleted",
    pleaseAddFundFlowFirst: "Please add fund flow records first",
    allocationExceeds: "Allocation amount exceeds net investment",
    allocationUpdated: "Product allocation updated (Total {n}%)",
    loginAttemptsLeft: "{n} login attempts remaining",
    loginLocked: "Account locked due to too many failed attempts",
    accountLocked: "Account locked, please try again in {n} minutes",
    pleaseEnterProductCode: "Please enter product code",
    pleaseEnterProductName: "Please enter product name",
    pleaseEnterValidAmount: "Please enter valid investment amount",
    pleaseEnterValidValue: "Please enter valid latest value",
    pleaseSelectProduct: "Please select product",
    pleaseSelectDate: "Please select date",
    pleaseEnterValidPrice: "Please enter valid value",
    pleaseSelectInvestor: "Please select investor",
    pleaseEnterTitle: "Please enter title",
    pleaseEnterDetail: "Please enter detail",
    pleaseEnterPlatform: "Please enter platform",
    transactionAmountInvalid: "Transaction {n} amount invalid",
    transactionDateMissing: "Transaction {n} missing date",
    pleaseEnterValidInterest: "Please enter valid interest amount",
    interestSaved: "Interest record saved",
    demoAccount: "Demo",
    viewInvestorView: "View Investor View",
    backToAdminView: "Back to Admin View",
    viewAsAdmin: "View as Admin",
    undefined: "Undefined",
    currentStatus: "Current Status",
    versionHistory: "Version History",
    dataUpdateRecord: "Data Update Record",
    netAssetData: "NAV & Asset Data",
    lastUpdateTime: "Last Update Time",
    snapshotDateSaved: "Snapshot date saved",
    investorNotFound: "Investor information not found. Please log in again.",
    adminViewMode: "Admin View Mode",
    backToAdmin: "Back to Admin",
    dataUpdateDate: "Data updated: ",
    exportPDF: "Export PDF",
    totalInterestPaid: "Total Interest Paid",
    interestCount: "Interest Payments",
    fundDistribution: "Fund Distribution",
    portfolioAllocation: "Portfolio Allocation",
    noInvestmentData: "No investment data",
    interestTrend: "Interest Trend",
    cumulativeInterest: "Cumulative Interest",
    productVolatility: "Product Volatility",
    productValueTrend: "Product Value Trend",
    allPhases: "All Phases",
    phase2: "Phase 2",
    phase1: "Phase 1",
    noProductData: "No product data",
    investmentPerformance: "Investment Performance",
    productReturnAnalysis: "Product Return Analysis",
    interestRecords: "Interest Records",
    recentInterestDetails: "Recent Payments",
    paymentDate: "Payment Date",
    paymentPlatform: "Platform",
    interestAmount: "Amount",
    remark: "Note",
    portfolioAnalysis: "Portfolio Analysis",
    riskReturnAssessment: "Risk & Return",
    investmentProductCount: "Products",
    averageReturn: "Avg Return",
    bestPerformingProduct: "Top Performer",
    lastUpdated: "Last Updated",
    totalValue: "Total Value",
    totalProfit: "Total Profit",
    investmentPeriod: "Investment Period",
    days: "days",
    recentNotices: "Recent Notices",
    invested: "Invested",
    valuation: "Valuation",
    percentage: "Weight",
    return: "Return",
  },
  "zh-hant": {
    save: "儲存", cancel: "取消", confirm: "確定", delete: "刪除",
    add: "新增", edit: "編輯", export: "匯出", import: "匯入",
    reset: "重置", logout: "登出", login: "登入", update: "更新",
    actions: "操作", loading: "載入中…",
    brandName: "愷皓資本", brandTagline: "專業資產管理，穩健增值",
    entryPortal: "身份入口", entryDesc: "選擇身份後進入對應視圖",
    investorLogin: "投資者登入", adminLogin: "管理員登入",
    switchToAdmin: "切換管理員", switchToInvestor: "切換投資者",
    investorId: "投資者編號", username: "使用者名稱", password: "密碼",
    phoneLastFour: "手機號後四位",
    investorLoginHint: "輸入姓名與密碼登入", adminLoginHint: "輸入管理員使用者名稱與密碼",
    platformOverview: "平台概覽", adminConsole: "管理後台",
    verifiedAccess: "已驗證", currentUser: "目前", notLoggedIn: "未登入",
    snapshot: "快照", investorCount: "位投資者", investorCountLabel: "投資者人數", backToMenu: "返回主選單",
    totalPrincipal: "管理本金", latestValuation: "最新估值",
    cumulativeReturn: "累計收益",
    investorProfile: "投資者資料", allocations: "投資方向",
    notices: "溝通紀要",
    bestAllocation: "最佳方向", totalInvested: "累計投入",
    profit: "浮動盈虧", returnRate: "累計收益率",
    riskLevel: "風險偏好", advisor: "顧問團隊",
    joinedAt: "建倉日期", lastReview: "最近更新",
    email: "聯絡信箱", phone: "手機號碼", name: "姓名",
    directionName: "方向名稱", directionFocus: "投資說明",
    directionCode: "策略代碼", amountInvested: "投入金額",
    latestValue: "最新估值",
    noticeDate: "紀要日期", noticeTitle: "紀要標題", noticeDetail: "紀要詳情",
    adminConsoleDesc: "管理投資者與溝通紀要，匯入匯出數據",
    userManagement: "使用者管理", userManagementDesc: "新增、編輯、刪除投資者帳號",
    productManagement: "產品管理", productManagementDesc: "錄入產品名稱、投資平台、出入金明細、備註等資訊",
    dataManagement: "數據管理", dataManagementDesc: "匯出 JSON、匯入 JSON / Excel、重置數據",
    addUser: "新增投資者",
    loginUsernames: "登入使用者名稱", loginUsernamesPlaceholder: "輸入使用者名稱後點擊新增",
    exportData: "匯出數據", exportDataDesc: "將目前所有平台數據匯出為 JSON 檔案，用於備份或遷移。",
    importData: "匯入數據", importDataDesc: "從 JSON 或 Excel 檔案匯入數據，JSON 匯入將覆蓋目前數據，Excel 匯入將追加投資者。",
    excelFormat: "Excel 欄位格式",
    resetDemoData: "重置數據", resetDemoDataDesc: "清除所有目前數據，恢復為空數據狀態，此操作不可撤銷。",
    dataStructureNote: "數據結構說明",
    dataStructureDesc: "數據以標準 JSON 格式持久化到瀏覽器 localStorage。可直接映射為後端資料庫表：investors、allocations、notices、admin_users。接入真實後台時，替換 數據操作.js 中的 loadData / saveData 即可無縫遷移。",
    exportJSON: "匯出 JSON", importJSON: "匯入 JSON",
    importExcel: "匯入 Excel", resetData: "重置數據",
    selectInvestor: "選擇投資者", saveInvestor: "儲存資料",
    addAllocation: "新增投資方向",
    addNotice: "儲存紀要",
    flashLoggedIn: "登入成功，歡迎回來。",
    flashLoggedOut: "已登出。",
    flashLoginFailed: "帳號或密碼錯誤，請重試。",
    flashSaved: "已儲存。",
    flashDeleted: "已刪除。",
    flashImported: "數據匯入成功。", flashImportedCount: "數據匯入成功，共處理 {n} 條。",
    flashExported: "數據匯出成功。",
    flashReset: "數據已重置。",
    flashError: "操作失敗，請檢查填寫內容。",
    noData: "暫無數據",
    noAllocations: "尚未錄入投資方向",
    noNotices: "尚未錄入溝通紀要",
    riskConservative: "穩健型", riskBalanced: "平衡型", riskAggressive: "積極型",
    riskLow: "低風險", riskMedium: "中風險", riskHigh: "高風險",
    totalInvestment: "累計投入",
    investorList: "投資者清單",
    total: "共",
    confirmDeleteInvestor: "確定要刪除投資者 {id} 的所有數據嗎？此操作不可撤銷。",
    confirmDeleteProduct: "確定要刪除產品嗎？",
    confirmResetData: "確定要重置所有數據為空數據狀態嗎？",
    errorInvestorIdRequired: "投資者編號不能為空。",
    errorNameRequired: "姓名不能為空。",
    errorPasswordRequired: "密碼不能為空。",
    errorPasswordMismatch: "兩次密碼輸入不一致。",
    errorInvestorNotFound: "未找到投資者。",
    errorAmountRequired: "金額不能為空或零。",
    errorImportFailed: "匯入失敗：{msg}",
    errorExcelImportFailed: "Excel 匯入失敗：{msg}",
    errorProductNotFound: "未找到產品。",
    accountCreated: "帳戶建立", accountCreatedDetail: "帳戶已錄入平台。",
    product: "產品", productName: "產品名稱", productCode: "產品代碼",
    platform: "投資平台", transactions: "出入金明細",
    deposit: "入金", withdrawal: "出金", netAmount: "淨金額",
    totalDeposits: "總入金", totalWithdrawals: "總出金",
    notes: "備註", noTransactions: "暫無交易記錄",
    amount: "金額", note: "備註", transaction: "交易記錄",
    pleaseFillDateAmount: "請填寫日期和有效金額",
    fundFlowAdded: "出入金記錄已新增",
    confirmDeleteFundFlow: "確認刪除此出入金記錄？",
    fundFlowDeleted: "出入金記錄已刪除",
    pleaseAddFundFlowFirst: "請先新增出入金記錄",
    allocationExceeds: "分配金額超過淨投入",
    allocationUpdated: "產品分配已更新（總計 {n}%）",
    loginAttemptsLeft: "登入失敗，還有{n}次嘗試機會",
    loginLocked: "登入失敗次數過多，帳戶已被鎖定5分鐘",
    accountLocked: "帳戶已被鎖定，請{n}分鐘後再試",
    pleaseEnterProductCode: "請輸入產品代碼",
    pleaseEnterProductName: "請輸入產品名稱",
    pleaseEnterValidAmount: "請輸入有效的投資金額",
    pleaseEnterValidValue: "請輸入有效的最新價值",
    pleaseSelectProduct: "請選擇產品",
    pleaseSelectDate: "請選擇日期",
    pleaseEnterValidPrice: "請輸入有效的價值",
    pleaseSelectInvestor: "請選擇投資者",
    pleaseEnterTitle: "請輸入標題",
    pleaseEnterDetail: "請輸入詳情",
    pleaseEnterPlatform: "請輸入平台",
    transactionAmountInvalid: "第{n}條交易記錄金額無效",
    transactionDateMissing: "第{n}條交易記錄缺少日期",
    pleaseEnterValidInterest: "請輸入有效的利息金額",
    interestSaved: "利息記錄已儲存",
    demoAccount: "演示",
    viewInvestorView: "查看投資者視角",
    backToAdminView: "返回管理員視角",
    viewAsAdmin: "管理員查看",
    undefined: "未定",
    currentStatus: "目前狀態",
    versionHistory: "版本更新記錄",
    dataUpdateRecord: "數據更新記錄",
    netAssetData: "淨值 & 資產數據",
    lastUpdateTime: "上次更新時間",
    snapshotDateSaved: "數據更新時間已儲存",
    investorNotFound: "投資者資訊不存在，請重新登入。",
    adminViewMode: "管理員檢視模式",
    backToAdmin: "返回管理後台",
    dataUpdateDate: "數據更新日期：",
    exportPDF: "匯出PDF報告",
    totalInterestPaid: "累計發放利息",
    interestCount: "利息發放次數",
    fundDistribution: "資金分布",
    portfolioAllocation: "投資組合占比",
    noInvestmentData: "暫無投資數據",
    interestTrend: "利息發放趨勢",
    cumulativeInterest: "累計利息走勢",
    productVolatility: "產品波動",
    productValueTrend: "各產品價值變化趨勢",
    allPhases: "全部階段",
    phase2: "第二階段",
    phase1: "第一階段",
    noProductData: "暫無產品數據",
    investmentPerformance: "投資表現",
    productReturnAnalysis: "各產品收益分析",
    interestRecords: "利息發放記錄",
    recentInterestDetails: "最近發放明細",
    paymentDate: "發放日期",
    paymentPlatform: "發放平台",
    interestAmount: "利息金額",
    remark: "備註",
    portfolioAnalysis: "組合分析",
    riskReturnAssessment: "風險與收益評估",
    investmentProductCount: "投資產品數",
    averageReturn: "平均收益率",
    bestPerformingProduct: "最高收益產品",
    lastUpdated: "最近更新",
    totalValue: "總估值",
    totalProfit: "總收益",
    investmentPeriod: "投資期限",
    days: "天",
    recentNotices: "最近溝通紀要",
    invested: "投入",
    valuation: "估值",
    percentage: "占比",
    return: "收益",
  }
};

export default i18n;